#ifndef EXAMPLEPLUGIN_GLOBAL_H
#define EXAMPLEPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(EXAMPLEPLUGIN_LIBRARY)
#  define EXAMPLEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define EXAMPLEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLEPLUGIN_GLOBAL_H
